"""
Книга
"""
type Book {
  id: String!
  title: String
  subtitle: String
  description: String
  image: String
  previewLink: String
  greenLink: String
  """
  Дата, поддерживает форматирование с помощью moment.js
  """
  date(format: String = "DD.MM.YYYY"): String
}
